#!/bin/sh
# aowlup installer — the one piece of this toolchain that is NOT written in the
# language, and cannot be: it runs on a machine that has none of it yet.
#
#   curl -fsSL https://raw.githubusercontent.com/aoughwl/aowlup/main/install.sh | sh
#
# It downloads a prebuilt `aowlup` for this platform, verifies its checksum, and
# puts it in ~/.aowl/bin. Everything after that — the compiler, the driver, the
# backends — `aowlup setup` installs, because by then there is a manager to do it.
#
# POSIX sh on purpose. No bashisms, no jq, no python: curl, sha256sum (or
# shasum), uname, mkdir, mv.
set -eu

# --- from a checkout: ./install.sh --local -----------------------------------
# Installs THIS checkout instead of a release asset. It is the only path on a
# platform with no published binary (Windows today), and the path a dev box
# takes when it wants the tree it is editing. What lands in ~/.aowl/bin:
#
#   aowl          the Node implementation, copied. This is the file the driver
#                 reads the registry through — aowlmony's loadStack() spawns
#                 `node ~/.aowl/bin/aowl config` — so it is a copy, not a link:
#                 a half-edited checkout must not break every compile on the box.
#   aowlup        the Nimony build (bin/aowlup-ng) where it runs; else a launcher
#                 for `aowl`. The Nimony build shells out through `sh -c`
#                 (mkdir -p, chmod, test -x …), which a mingw binary hands to
#                 cmd.exe, so on Windows it is built for parity but not installed.
#   aowlup.cmd    Windows only: the same launcher for cmd / PowerShell.
LOCAL=0
for a in "$@"; do case "$a" in --local) LOCAL=1 ;; esac; done

REPO="${AOWLUP_REPO:-aoughwl/aowlup}"
CHANNEL="${AOWLUP_CHANNEL:-latest}"
AOWL_HOME="${AOWL_HOME:-$HOME/.aowl}"
BIN_DIR="$AOWL_HOME/bin"

say()  { printf '  %s\n' "$*"; }
die()  { printf '  x %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "need '$1' on PATH"; }
need curl
need uname
need mkdir

# --- platform ---------------------------------------------------------------
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$os" in
  linux)  os=linux ;;
  darwin) os=macos ;;
  mingw*|msys*|cygwin*) os=windows ;;
  *) die "unsupported OS '$os' — build from source: https://github.com/$REPO" ;;
esac
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  aarch64|arm64) arch=arm64 ;;
  *) die "unsupported architecture '$arch'" ;;
esac
TRIPLE="$os-$arch"
ASSET="aowlup-$TRIPLE"

if [ "$LOCAL" = 1 ]; then
  here="$(cd "$(dirname "$0")" && pwd)"
  [ -f "$here/bin/aowlup" ] || die "--local needs to run from an aowlup checkout (no $here/bin/aowlup)"
  need node
  say "aowlup installer  ·  $TRIPLE  ·  from checkout $here"
  mkdir -p "$BIN_DIR"
  cp "$here/bin/aowlup" "$BIN_DIR/aowl"
  chmod 755 "$BIN_DIR/aowl"
  say "installed $BIN_DIR/aowl  (Node build; what aowlmony reads the registry through)"
  ng=""
  for c in "$here/bin/aowlup-ng" "$here/bin/aowlup-ng.exe"; do [ -f "$c" ] && ng="$c" && break; done
  if [ -n "$ng" ] && [ "$os" != windows ] && "$ng" config >/dev/null 2>&1; then
    cp "$ng" "$BIN_DIR/aowlup"
    chmod 755 "$BIN_DIR/aowlup"
    say "installed $BIN_DIR/aowlup  (Nimony build)"
  else
    [ -n "$ng" ] && say "bin/aowlup-ng is built but not installed on $os — its shell-outs need a POSIX sh"
    printf '#!/bin/sh
# generated by install.sh --local: the Node build of aowlup
AOWLUP_PROG=aowlup exec node "$(dirname "$0")/aowl" "$@"
' > "$BIN_DIR/aowlup"
    chmod 755 "$BIN_DIR/aowlup"
    say "installed $BIN_DIR/aowlup  (launcher for aowl)"
    if [ "$os" = windows ]; then
      printf '@echo off
rem generated by install.sh --local: the Node build of aowlup
set AOWLUP_PROG=aowlup
node "%%~dp0aowl" %%*
' > "$BIN_DIR/aowlup.cmd"
      say "installed $BIN_DIR/aowlup.cmd"
    fi
  fi
  printf '
'
  say "add to PATH →  export PATH=\"$BIN_DIR:\$PATH\""
  say "then       →  aowlup init    (register what is built on this machine)"
  printf '
'
  exit 0
fi
[ "$os" = windows ] && die "no Windows release is published — from a checkout run: ./install.sh --local"

# --- the digest tool differs between Linux and macOS ------------------------
sha_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    echo ""
  fi
}

# --- locate the release ------------------------------------------------------
if [ "$CHANNEL" = "latest" ]; then
  API="https://api.github.com/repos/$REPO/releases/latest"
else
  API="https://api.github.com/repos/$REPO/releases/tags/$CHANNEL"
fi

say "aowlup installer  ·  $TRIPLE  ·  $REPO ($CHANNEL)"

json="$(curl -fsSL -H 'Accept: application/vnd.github+json' "$API" 2>/dev/null)" || json=""

# `/releases/latest` EXCLUDES pre-releases, so a project whose only releases are
# pre-releases has no "latest" at all — which is exactly the state a new project
# is in, and an installer that dies there is broken for its whole early life.
# Fall back to the releases LIST and take the newest entry.
if [ -z "$json" ] && [ "$CHANNEL" = "latest" ]; then
  say "no stable release yet — falling back to the newest pre-release"
  json="$(curl -fsSL -H 'Accept: application/vnd.github+json' \
          "https://api.github.com/repos/$REPO/releases?per_page=1" 2>/dev/null | sed '1s/^\[//; $s/\]$//')"
fi
[ -n "$json" ] || die "could not reach GitHub (or no such release: $CHANNEL)"

# Pull the download URL for our asset without jq: one URL per line, keep ours.
url="$(printf '%s' "$json" \
  | tr ',' '\n' \
  | grep 'browser_download_url' \
  | sed 's/.*"browser_download_url":[[:space:]]*"//; s/".*//' \
  | grep "/$ASSET$" \
  | head -1)"
[ -n "$url" ] || die "release has no asset named '$ASSET' — this platform is not published yet"

tag="$(printf '%s' "$json" | tr ',' '\n' | grep '"tag_name"' \
  | sed 's/.*"tag_name":[[:space:]]*"//; s/".*//' | head -1)"

# --- download, verify, install ----------------------------------------------
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

say "downloading $ASSET ${tag:+($tag)}"
curl -fsSL -o "$tmp/aowlup" "$url" || die "download failed"

if curl -fsSL -o "$tmp/aowlup.sha256" "$url.sha256" 2>/dev/null; then
  want="$(cut -d' ' -f1 < "$tmp/aowlup.sha256")"
  got="$(sha_of "$tmp/aowlup")"
  if [ -z "$got" ]; then
    say "! no sha256 tool available — installing UNVERIFIED"
  elif [ "$want" != "$got" ]; then
    die "checksum mismatch: expected $want, got $got"
  else
    say "checksum ok"
  fi
else
  say "! the release publishes no .sha256 for this asset — installing unverified"
fi

# Refuse EARLY if this machine's glibc is older than the binary needs. Without
# this the install "succeeds" and the first run dies in the dynamic loader with
# a message that names a symbol version and nothing the user can act on.
if curl -fsSL -o "$tmp/aowlup.glibc" "$url.glibc" 2>/dev/null; then
  need="$(cat "$tmp/aowlup.glibc")"
  have="$(ldd --version 2>/dev/null | head -1 | grep -o '[0-9]\+\.[0-9]\+' | tail -1)"
  if [ -n "$need" ] && [ -n "$have" ]; then
    lowest="$(printf '%s\n%s\n' "$need" "$have" | sort -V | head -1)"
    if [ "$lowest" = "$have" ] && [ "$have" != "$need" ]; then
      die "this build needs glibc >= $need and this system has $have — build from source instead: https://github.com/$REPO"
    fi
    say "glibc $have >= $need"
  fi
fi

mkdir -p "$BIN_DIR"
chmod 755 "$tmp/aowlup"
mv "$tmp/aowlup" "$BIN_DIR/aowlup"

say "installed $BIN_DIR/aowlup"
printf '\n'
say "add to PATH →  export PATH=\"$BIN_DIR:\$PATH\""
say "then       →  aowlup setup --yes    (installs the rest of the toolchain)"
printf '\n'
